name: Update README and add collaborator

on:
  push:
    branches:
      - main

jobs:
  add-collaborator:
    if: "!contains(github.repository.collaborators, 'github-actions[bot]')"
    runs-on: ubuntu-latest
    steps:
    - name: Add GitHub Actions bot as collaborator
      uses: actions/github-script@v4
      with:
        script: |
          const { Octokit } = require("@octokit/rest");
          const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
          await octokit.repos.addCollaborator({
            owner: "${{ github.repository_owner }}",
            repo: "${{ github.repository }}",
            username: "github-actions[bot]",
            permission: "write"
          })

  update-readme:
    runs-on: ubuntu-latest
    needs: add-collaborator
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        # Set the version of Node.js to use
        node-version: '16.x'

    - name: Configure Git
      run: |
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"

    - name: Update README 
      run: |
        echo $RANDOM > README.md

    - name: Push
      run: |
        git add README.md
        git commit -m "Update README"
        git push origin main

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: updated-readme
        path: README.md
